const constants = {
  FETCHING_RECIPES: 'FETCHING_RECIPES',
  DELETE_RECIPES: 'DELETE_RECIPES',
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
  EDIT_RECIPE: 'EDIT_RECIPE',
  ADD_RECIPE: 'ADD_RECIPE',
  FETCH_NEW_RECIPE: 'FETCH_NEW_RECIPE'
}

export default constants
